### ISSUE TITLE
error 403 forbidden

### ISSUE THREAD

**Issue by armory09** [spring-guides/gs-consuming-rest#9]
when i try to build the sample app with gradle i get an error 403 forbidden

here is the stacktrace

14:48:40.048 [main] DEBUG o.s.web.client.RestTemplate - Created GET request for "http://graph.facebook.com/pivotalsoftware"
14:48:40.080 [main] DEBUG o.s.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
14:48:40.547 [main] DEBUG o.s.web.client.RestTemplate - GET request for "http://graph.facebook.com/pivotalsoftware" resulted in 403 (Forbidden); invoking error handler
Exception in thread "main" org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:237)
        at hello.Application.main(Application.java:13)
:run FAILED  

i hope you can help me

**Comment by dsyer** [comment]
You probably exceeded a rate limit or something. Try again in an hour or two.

**Comment by armory09** [comment]
i try it again after 5 hrs still failed with the same error mention above

**Comment by armory09** [comment]
it did work when i use the sample gs-rest-service and consuming it to gs-consuming-rest

Thank you very much for this
